# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code And Wave
email: nelzkie.coder@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just Code and Wave coders. Just Code and Wave
baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "" # change this to the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]

# permalink: /:categories/:year/:month/:day/:title.html
# none is equivalent to /:title.html
# https://jekyllrb.com/docs/permalinks
permalink: /:title.html

# highlighter: pygments



# gem:
#   - jekyll-email-protect
#   - jekyll-seo-tag

# plugins:
#   # - jekyll-seo-tag
#   # - jekyll-feed
#   - jekyll-email-protect
  

google_analytics:

# jekyll-theme-simple-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
jekyll-theme-simple-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

show_post_image_posts_list: false

header:
  image: /assets/patterns/symphony.png

# social
author:
  name: "Nelzkie"
  short_bio:
    en: nelzkie.coder@gmail.com

  picture: assets/img/profile-60.png

image: /assets/img/profile-225.png

#twitter:
#  username:
#instagram_username:

#linkedin_username: lorepirri

#  site:
facebook:
  publisher_id: 
  profile_id: 
  app_id: 
  authors: []
  #pixelcode: 1670622619859349


# gitlab on site
gitlab:
  owner_url: 

# github on site
github:
  owner_url: 


twitter:
  username: CodeandWave

# translation

t:
  en:
    latest-posts:  "Latest Posts"
    read-more:  "read more"
    on-word: "on"
    contact: "Contact"
    contact-page: "contact.md"
    read-time: "min read"
    comments: "comments"
    go-to-home-page: "Go to the Home Page"
    months:
      january: "Jan"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "May"
      june: "Jun"
      july: "Jul"
      august: "Aug"
      september: "Sep"
      october: "Oct"
      november: "Nov"
      december : "Dec"


defaults:
  -
    scope:
      type: "posts"
    values:
      lang: "en"
      category: articles



